"""Added data

Revision ID: e2e98abb2e15
Revises: 27488b9c7bc4
Create Date: 2023-07-26 13:18:15.959183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e98abb2e15'
down_revision = '27488b9c7bc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
